server:
  port: 8888
spring:
  zipkin:
    enabled: true
    base-url: ${ZIPKININ_URLSI}
    service:
      name: config-service
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/MFurkanTurkmen/ConfigCloudPawer.git"
          default-label: main
          skip-ssl-validation: true
          username: MFurkanTurkmen
          password: ${GIT_PASSWORD}