server:
  port: 6160

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: driver-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB



  data:
    mongodb:
      host: localhost   #localhost
      port: 29000    # buse:29000 , furkan:27000
      username: ${MONGOPAWERPOSTUSERNAME}
      password: ${MONGOPAWERPOSTPASSWORD}
      database: PostDB
myproject:
  google:
    storage:
      bucketname: socialmediaavatar

